name: Test Simple Workflow

on:
  workflow_dispatch:  # Manual trigger only for testing

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Test Python
      run: |
        python --version
        echo "Current directory:"
        pwd
        echo "Files in directory:"
        ls -la
    
    - name: Create test file
      run: |
        echo "Test at $(date)" > test_file.txt
    
    - name: Try to commit
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add test_file.txt
        git commit -m "Test commit" || echo "No changes to commit"
        git push || echo "Push failed"